version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/templates/
    environment:
    - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
    - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always


  mysql:
    image: mysql
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./mysql-db:/var/lib/mysql
    depends_on:
      - wordpress
    environment:
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
        MYSQL_DATABSE:  ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  