version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/templates/
    environment:
    - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
    - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always


  mysql:
    image: mysql
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./mysql-db:/var/lib/mysql
    depends_on:
      - wordpress
    environment:
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
        MYSQL_DATABSE:  ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    container_name: ${APP_NAME}-wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST:  mysql
      WORDPRESS_DB_NAME:  ${DB_NAME}
      WORDPRESS_DB_USER:  ${DB_USER}
      WORDPRESS_DB_PASSWORD:  ${DB_PASSWORD}
      PHP_INI_UPLOAD_MAX_FILESIZE: 256M
    restart: always

